'use client'
import { Inter } from "next/font/google";
import {useState} from 'react'
import "./globals.css";
import { Header, NavMenu } from "./_components";
import Dashboard from "./(pages)/page";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [navigationItemsList, setNavigationItemsList] = useState([{
    id: 1,
    name: 'Dashboad',
    isActive: true,
    icon: ``,
    navigationUrl: `/`
  },
  {
    id: 2,
    name: 'Orders',
    isActive: false,
    icon: ``,
    navigationUrl: `/orders`
  },
  {
    id: 3,
    name: 'Customers',
    isActive: false,
    icon: ``,
    navigationUrl: `/customers`
  },
  {
    id: 4,
    name: 'Manage Staff',
    isActive: false,
    icon: ``,
    navigationUrl: `/manage-staff`
  }]);

  return (
    <html lang="en">
      <Header />
      <NavMenu navigationItemsList={navigationItemsList}/>
      <Dashboard />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
